
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${JWT_EXPIRATION} # a day
      refresh-token:
        expiration: 604800000 # 7 days


cloudinary:
  cloud-name: dnfqh0xor
  api-key: 824374795628962
  api-secret: ZkW3BqawOuplLWv2Kq--llPkWlk
  secure: true

twilio:
  account-sid:
  auth-token:
  outgoing-sms-number: 